FROM python:3.12.2
LABEL maintainer="tvijverb"

# make sure debian/ubuntu know we can't use keyboard interactions during build
ENV DEBIAN_FRONTEND=noninteractive

# Keeping the image up to date and installing node 15
RUN apt-get update -y && apt-get upgrade -y && \
    rm -rf /var/lib/apt/lists/*

# setup flask application directory
RUN mkdir /app
WORKDIR /app

# Create a non-root user and switch to it
RUN adduser --disabled-password --gecos '' --shell /bin/bash user && chown -R user:user /app
# RUN echo "user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/90-user
USER user

# All users can use /home/user as their home directory
ENV HOME=/home/user
RUN chmod 777 /home/user
RUN cd /home/user

COPY requirements/ requirements/

RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements/dev.txt

COPY . .

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--reload"]